server:
  port: ${PORT:4444}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: client
#          uri: lb://client-service
#          predicates:
#            - Path=/api/client
#            - Method=GET

logging:
  level:
    web: DEBUG
