server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mrrnyash/eureka-config
          searchPaths: "/ms-config-properties/{application}/{profile}"
          default-label: main
          username: mrrnyash
          password: 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

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}